set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

bind -n M-H previous-window
bind -n M-L next-window


# Use Alt-arrow keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D


bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set  -g @plugin 'tmux-plugins/tpm'
set  -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'

set -g @tmux-gruvbox 'dark'

run '~/.tmux/plugins/tpm/tpm'

bind-key C-b send-prefix

# set vi-mode
set-window-option -g mode-keys vi

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind ù split-window -h -c "#{pane_current_path}"

set escape-time 300
set focus-events
